bundler_args: --without development
gemfile:
  - Gemfile
  - Gemfile.rack-1.3.x
language: ruby
rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
